In [1]:
import torch

In [2]:
randint = torch.randint(-100,100,(6,))
randint

tensor([ 24, -69,   9, -81,   0,  33])

In [3]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
input = torch.empty(2,3)
input

tensor([[-8.9875e-08,  1.1687e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [5]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [6]:
linspace = torch.linspace(3,10,steps = 5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [7]:
logspace = torch.logspace(start= -10, end= 10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [8]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [9]:
a = torch.empty((2,3), dtype = torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [10]:
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [11]:
%%time
start_time = time.time()
for i in range(10000):
    loss=i
end_time=time.time()
elapsed_time = end_time-start_time
print(f"{elapsed_time:.8f}")

0.00100017
CPU times: total: 0 ns
Wall time: 1 ms


In [12]:
# torck.stack, torch.multinomial, torhc.trill, troch.triu, input.T/input.transpose, nn.linear, torch.cat, F.softmax

# Define a probability tensor
probability = torch.tensor([0.1,0.9])
# 10% or 0.1 of 0 and 90% o 0.9 of 1 
# Draw 5 examples from the multinomial distribution
samples = torch.multinomial(probability, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [13]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor,torch.tensor([5])),dim=0)
out

tensor([1, 2, 3, 4, 5])

In [14]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [15]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [16]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0,float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [17]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [18]:
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [19]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

stacked_tensor = torch.stack([tensor1,tensor2,tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [20]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3,bias=False)
print(linear(sample))

tensor([-5.8724,  4.2757, -0.1458], grad_fn=<SqueezeBackward4>)


In [21]:
import torch.nn.functional as F
sample = torch.tensor([1.,2.,3.])
softmax= F.softmax(sample,dim=0)
print(softmax)

tensor([0.0900, 0.2447, 0.6652])


In [43]:
import torch
import torch.nn as nn

# Define the size of the vocabulary and the embedding dimension
vocab_size = 1000
embedding_dim = 3

# Create an Embedding layer
embedding_layer = nn.Embedding(num_embeddings=vocab_size, embedding_dim=embedding_dim)

# Define a batch of input indices (e.g., token indices)
input_indices = torch.tensor([1, 2, 3, 4])

# Get the embeddings for the input indices
embeddings = embedding_layer(input_indices)

print(embeddings)


tensor([[ 1.1139, -0.7569, -0.0700],
        [-0.2938, -2.0198, -1.6255],
        [ 2.2112,  0.5965, -0.5139],
        [ 0.4604, -0.7912,  0.1202]], grad_fn=<EmbeddingBackward0>)


In [59]:
a = torch.tensor([[1,2,3]])
b = torch.tensor([[4,5,6]])
print(a,a.shape)
print(b,b.shape)
print(a@b.T)

tensor([[1, 2, 3]]) torch.Size([1, 3])
tensor([[4, 5, 6]]) torch.Size([1, 3])
tensor([[32]])


In [67]:
int_64 = torch.randint(1,(3,2)).float()
float_32 = torch.rand((3,2))
print(int_64.dtype, float_32.dtype)

torch.float32 torch.float32
